### ISSUE TITLE
Google Play rejection (PendingIntent issue)

### ISSUE THREAD

**Issue by KrzysztofMamak** [HMS-Core/hms-flutter-plugin#100]
**Description**
Google Play Store rejected our app which uses huawei_push package, because of PendingIntent issues (security reasons).
We want to use the same source code for Google Play Store and Huawei App Gallery.

**Expected behavior**
We want to follow all Google Play Store security rules.

**Current behavior**
Google Play Store rejected our app because of security rules.

**Environment**
 - Platform: Flutter
 - Kit: Push
 - Kit Version: 5.1.1+301
 - Location/Region: Poland

How we can use the same source code for Google Play Store and Huawei App Gallery? We should omit huawei_push_dependency in the whole project (avoid pubspec dependency) or just not using huawei_push in built APK (Google Play Store)?

**Comment by atavci** [comment]
Hello @KrzysztofMamak ,

As you pointed out Google recenty released the [Remediation for Implicit PendingIntent Vulnerability](https://support.google.com/faqs/answer/10437428?hl=en) that enforces developers to update their code that uses PendingIntents. 

In order to display notifications, Huawei Push Kit uses PendingIntents implicitly and this causes the problem. On the next release for the Push Kit Flutter Plugin the issues related PendingIntents will be fixed, you may check the [Huawei Developers Website](https://developer.huawei.com/consumer/en/doc/development/HMS-Plugin-Guides/version-change-history-0000001050417995) for the updates. By the meantime the only way to get approved by the Play Store seems to avoid the pubspec dependency. 

Thank you for your patience and for pointing out this issue,
Best.

**Comment by ferenclakos** [comment]
Hi guys!

We look forward to the next release which will solve this issue (on pub.dev). Could you tell us when you will update the kit version to 5.3.0.304?

Thank you.

**Comment by KrzysztofMamak** [comment]
> Hello @KrzysztofMamak ,
> 
> As you pointed out Google recenty released the [Remediation for Implicit PendingIntent Vulnerability](https://support.google.com/faqs/answer/10437428?hl=en) that enforces developers to update their code that uses PendingIntents.
> 
> In order to display notifications, Huawei Push Kit uses PendingIntents implicitly and this causes the problem. On the next release for the Push Kit Flutter Plugin the issues related PendingIntents will be fixed, you may check the [Huawei Developers Website](https://developer.huawei.com/consumer/en/doc/development/HMS-Plugin-Guides/version-change-history-0000001050417995) for the updates. By the meantime the only way to get approved by the Play Store seems to avoid the pubspec dependency.
> 
> Thank you for your patience and for pointing out this issue,
> Best.

We decided to modify dependencies on pipeline based on targeted platform. After releasing new version in Google Play Store I will send a feedback. Note that Google Play Store didn't rejected our app in review (before release).
