### ISSUE TITLE
Does Huawei Push Kit work for iOS app created with Flutter?

### ISSUE THREAD

**Issue by reverseapp** [HMS-Core/hms-flutter-plugin#113]
This may be stupid question )

Bu there are what I know so far:

- Official site says:

> Supports Android (with HMS) apps, iOS apps, web apps, and Huawei quick apps.

- iOS therefore dos not have HMS

If it supports, is there any additional steps to make it work? And, same question for AGConnect Crash. Thank you!

**Comment by atavci** [comment]
Unfortunately the Flutter Push Kit plugin does not support iOS by the meantime. For your questions about AGC please visit the [agc-flutter github repository](https://github.com/AppGalleryConnect/agc-flutter-plugin) or [Huawei Developers](https://developer.huawei.com/consumer/en/) website.

**Comment by reverseapp** [comment]
@atavci Got it. But how can I send push notifications to iOS users in China?

**Comment by atavci** [comment]
Since Push Kit Flutter Plugin only supports Android platform for the time being, you may integrate Native Huawei Push Kit SDK to your iOS project and implement platform specific code to be able to send notifications to iOS users. Here is [the document for the development process](https://developer.huawei.com/consumer/en/doc/development/HMSCore-Guides/ios-dev-progress-0000001062221191#section117721135155110). For questions related to native SDK please [submit a ticket online](https://developer.huawei.com/consumer/en/support/feedback/#/).

**Comment by reverseapp** [comment]
Thank you very much!
