### ISSUE TITLE
关于ScanKitFrameWork支持bitcode

### ISSUE THREAD

**Issue by devcxm** [HMS-Core/hms-flutter-plugin#137]
您好，请问iOS的依赖库`ScanKitFrameWork.framework`是否可以考虑支持bitcode？如果一个库不支持bitcode，会导致整个项目和App包也没办法支持bitcode，这样苹果就没有办法针对不同架构的设备进行大小优化，导致安装包非常庞大。

**Comment by SerdarCanDev** [comment]
Hi @devcxm , thank you for your interest in our Scan Kit Flutter Plugin. 

Since our Flutter plugin is a wrapper for native Android Huawei Scan Kit and does not currently support the iOS platform, you may check [FAQs](https://developer.huawei.com/consumer/en/doc/development/HMSCore-Guides/faq-0000001050747017) of the native SDK for further help. If it doesn't help you can always [submit a ticket online](https://developer.huawei.com/consumer/en/support/feedback/#/) for your native SDK related questions.
