### ISSUE TITLE
[huawei_push] I banned from receiving notifications

### ISSUE THREAD

**Issue by mustafa-707** [HMS-Core/hms-flutter-plugin#150]
**Description**
Hello , I was testing a new feature that's depend on sending notification , so I start to push notification many time to my Huawei device and everything is ok till it suddenly stopped working from receiving notification  by token , and when i tried to send notifications the send API is responded with success  , So now I cant receive any Huawei push notification on my device , is there's a limitation , it's a bug or .. etc.

 I tried to send by topic or anything else but it looks the device banned from receiving notifications.

also before that I was sending by topic and now it gives me `topic exceed` when try to subscribe a specific topic 

on the first of the problem i received this but now it return to success and still not receiving : 

```
 {“code”:“80300007",“msg”:“All the tokens are invalid”,“requestId”:“164011770176983990000507"}
```

**Environment**
 - Platform: Flutter
 - Kit: Push
 - Kit Version 5.3.0+304
 - OS Version Android 10
 - Android Studio version  4.1.2
 - Platform version Flutter 2.5.3 stable

**Comment by Joseph-Nathan** [comment]
@mustafa-707  what are you use to send the messages to huawei devices ?

**Comment by mustafa-707** [comment]
@Joseph-Nathan  
Hello ,
im using this :
https://forum.xda-developers.com/t/how-to-send-notification-to-devices-from-server-with-hms-push-kit.4088817/

method to send notification by using Huawei end-points and my app secrets Ids , which I do the first post to oauth login api then i take the token to the next one (push-api), I'm using tokens and topics usually tokens mostly if i sent more than 50+ push notification it blocks the phone but it comeback to receive after a 24 hour , but topic when i use same topic it gives me `topic exceed` message on app and not recive any notification by this `exceeded` topic

**Comment by ozkulbeng** [comment]
Hi @mustafa-707 
Sorry for the late response, I can see the error code **80300007** in your logs and as stated in [the official documents of Huawei Push Kit](https://developer.huawei.com/consumer/en/doc/development/HMSCore-Guides/commonerror-0000001059816656), the problem is caused by the invalid token.

You can try the following steps to fix the issue:
- In principle, the tokens of different apps on the same device are different. Actually, the same tokens may exist by mistake.
- The package name and app ID configured for the app on the device are different from those applied for in AppGallery Connect.
- Check whether the access token URL is correct.
- Check whether the message sending URL is correct.

If the error persists, do not hesitate to write back to us.
