### ISSUE TITLE
[huawei_map] Compatibility with Flutter 3

### ISSUE THREAD

**Issue by deckerst** [HMS-Core/hms-flutter-plugin#191]
Rendering of platform views was modified for Flutter 3, and `huawei_map` is affected by this issue: https://github.com/flutter/flutter/issues/103630

`huawei_map` should implement the fix described in this comment: https://github.com/flutter/flutter/issues/103630#issuecomment-1129224567

**Comment by sunnykinger** [comment]
Please fix this guys

**Comment by Dooks123** [comment]
totally absent.

**Comment by Xuejiao-Shi** [comment]
@deckerst @Dooks123 @sunnykinger 
Thank you guys for providing the information regarding this issue, development team is working on the solution now. It is expected that some of the features will be fixed in the new version, and some features will be updated after the Flutter Engine is updated. https://github.com/flutter/flutter/issues/103630

**Comment by awshakam1998** [comment]
any one can help me to solve this issue in StackOverFlow [https://stackoverflow.com/q/72711906/13220760](url)

**Comment by syahnurizal** [comment]
Any updates on this? I can't release new updates for my apps due to this bug

**Comment by Xuejiao-Shi** [comment]
@syahnurizal pls check this solution: https://github.com/HMS-Core/hms-flutter-plugin/issues/213#issuecomment-1176089281
