### ISSUE TITLE
We found your app is using a non-compliant version of Huawei Mobile Services SDK

### ISSUE THREAD

**Issue by mustafa-707** [HMS-Core/hms-flutter-plugin#193]
**Description**
Google play rejection 

**Current behavior**
 the app rejected for using HMS services.
**Screenshots**
![image](https://user-images.githubusercontent.com/74349843/172047626-8950e150-0aa7-4ed4-b935-d0226646ba52.png)

**Environment**
 - Platform: Flutter
 - Kit: Push/Ads/Account/IAP/location
 - Kit Version  latest
 - OS Version Android OS
 - Your Location/Region : Middle east

**Other**
is there any updates that must do to avoid this issue ?

**Comment by coolleizhu** [comment]
Can you share the app name and package name?
Which kit you used?

**Comment by mustafa-707** [comment]
@coolleizhu 

App name : ArabiaWeather
package : `com.arabiaweather.main_app`

kits : 
```
  huawei_location: ^6.0.0+302
  huawei_iap: ^6.2.0+301
  huawei_push: ^6.3.0+304
  huawei_account: ^6.1.0+302
  huawei_ads: ^13.4.45+308
  huawei_analytics: ^6.2.0+301
```

**Comment by ozkulbeng** [comment]
Hello @mustafa-707

**Comment by mustafa-707** [comment]
Hello @ozkulbeng  , 
 Thank you for the update , unfortunately i tried the new updates for all plugins and even with update one of them it appears a dialog for google only mobile phones , that ask for HMS Core SDK as the following screenshot: 
 
 
![image](https://user-images.githubusercontent.com/74349843/177646588-990524d6-2554-4cf5-af8d-78f1868a8595.png)

 and that experience is annoying the users who aren't use Huawei services on their devices and it could makes google notice that HMS services is declared

**Comment by ozkulbeng** [comment]
Hello again @mustafa-707 , 
Some of our plugins require support from the basic services provided by HMS Core, such as **HUAWEI ID** (huawei_account is in your list), game, and health services. Thus, they may require HMS Core to be installed or updated to the latest version to work properly. With the latest versions of our plugins, we've deleted the capability of prompting users to install HMS Core due to the issue that was reported from Google (as in your first message). So that users are expected to install or update HMS Core manually.
