### ISSUE TITLE
[huawei_iap] Support for verifying signature

### ISSUE THREAD

**Issue by deakjahn** [HMS-Core/hms-flutter-plugin#25]
In Java or Kotlin, we have the possibility to verify the incoming response with the public key because we have the incoming data itself in the `inAppPurchaseDataList/inAppPurchaseData` list, to be verified with the corresponding `inAppSignature/inAppDataSignature` entry. If verified, we can then go on to decode the data to use the contents.

But in Flutter, we don't receive the original JSON, we only receive the decoded version as a `InAppPurchaseData` type. The original JSON is already gone, so there is no way to verify it. It should be placed into a string in that type so that we can verify it.

**Comment by SerdarCanDev** [comment]
Hi @deakjahn,  there are three classes that return data signatures.  

- After purchasing an item, Huawei IAP Flutter Plugin will parse the JSON response and creates a `PurchaseResultInfo` class which includes `InAppPurchaseData` and corresponding `inAppDataSignature` as a String.
- After consuming an item, Huawei IAP Flutter Plugin will parse the JSON response and creates a `ConsumeOwnedPurchaseResult` class which includes `ConsumePurchaseData` and corresponding `dataSignature` as a String. 
- After requesting owned purchases, Huawei IAP Flutter Plugin will also parse the JSON response and creates an `OwnedPurchasesResult` which includes `inAppPurchaseDataList` as mentioned, and corresponding `inAppSignature` field in order to verify the purchases. 

Huawei IAP Flutter Plugin parses the entire JSON response without any loss, hence you may use the mentioned fields. In later releases, we will also add a field that returns the original JSON response to fulfill your request.

**Comment by deakjahn** [comment]
Yes, sure, there's no problem with the signatures themselves, just that the original JSON itself is not yet available. Thanks for the inlcusion in the future.

**Comment by deakjahn** [comment]
@serdar-can As far as I can tell, we're here more than three years later and even if Huawei itself calls this step mandatory, see https://developer.huawei.com/consumer/en/doc/HMSCore-Guides/verifying-inapppurchasedata-0000001494212281, we're still unable to perform it from the Flutter plugin. We should be able to verify the signature with the _original JSON payload_ and we need it in order to do so. The plugin parses the JSON for us which is very good and handy, of course, but it should **also** send the original JSON along for signature verification. Please, reach out to your own team who wrote the _mandatory_ requirement above and make sure that you're consistent at least inside the company. :-))
