### ISSUE TITLE
huawei_location 6.4.0+300 flutter web compilation error

### ISSUE THREAD

**Issue by petodavid** [HMS-Core/hms-flutter-plugin#263]
**Description**
My application has both mobile and web support and since I added the `huawei_location` package the dart2js compiler fails

**Expected behavior**
I know that the `huawei_location` plugin has android only support but web builds should not fail

**Current behavior**
The web builds are failing

**Logs**
```
../../../Developer/flutter/.pub-cache/hosted/pub.dartlang.org/huawei_location-6.4.0+300/lib/src/location/location_request.dart:123:23: Error: The integer literal 9223372036854775807 can't be represented exactly in JavaScript.
Try changing the literal to something that can be represented in Javascript. In Javascript 9223372036854775808 is the nearest value that can be represented exactly.
    _expirationTime = 9223372036854775807;
                      ^^^^^^^^^^^^^^^^^^^
Failed to compile application.
```
**Environment**
 - Platform: Flutter
 - Kit: `huawei_location`
 - Kit Version: `6.4.0+300`
 - OS Version: WEB

**Other**

I tried the following but I still can not solve it:

- Conditional Importing (https://gpalma.pt/blog/conditional-importing/)
- Ignoring the location kit flutter package on the web like this (https://github.com/dart-lang/build/blob/master/docs/faq.md#how-can-i-fix-assetnotfoundexceptions-for-swap-files)

**Comment by xuxiapu** [comment]
@petodavid _ expirationTime=9223372036854775807，The data volume of this value is too large, so the web platform cannot recognize it, which causes compilation failure;
The root cause is that the location's flutter plug-in is adapted for mobile phones, and the maximum design of Web applications is different from that of mobile phones, which leads to overflow.
Therefore, you can manually modify the default values, such as 9223372036854775807 to 4294967295, and then try to build again.
https://github.com/HMS-Core/hms-flutter-plugin/blob/master/flutter-hms-location/lib/src/location/location_request.dart
