### ISSUE TITLE
huawei_iap 60052  item not owned

### ISSUE THREAD

**Issue by AhmedAbogameel** [HMS-Core/hms-flutter-plugin#269]
i have purchase a subscription plan then used consumeOwnedPurchase function 
then i got this Exception :
`[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(60052, 60052: item not owned, null, null)`

my code is : 

`
final r = await IapClient.createPurchaseIntent(PurchaseIntentReq(
        productId: productID,
        priceType: IapClient.IN_APP_SUBSCRIPTION,
      ));
ConsumeOwnedPurchaseReq request = ConsumeOwnedPurchaseReq(purchaseToken:r.inAppPurchaseData!.purchaseToken!);
await IapClient.consumeOwnedPurchase(request);
`

Note that the subscription has been purchased on app gallery and throwing exception above 

i think this function can not be used on subscription which is non-consumable product

**Comment by ilsafarber** [comment]
@AhmedAbogameel since subscriptions are not regarded as consumables, you can not use the [consumeOwnedPurchase](https://developer.huawei.com/consumer/en/doc/development/HMS-Plugin-References-V1/iap-client-0000001051085612-V1#section272817141261) method for them. So, you only need to call the [createPurchaseIntent](https://developer.huawei.com/consumer/en/doc/development/HMS-Plugin-References-V1/iap-client-0000001051085612-V1#section731513141419) method to start a subscription defined in the AppGallery Connect page for your app. As the name suggests, [consumeOwnedPurchase](https://developer.huawei.com/consumer/en/doc/development/HMS-Plugin-References-V1/iap-client-0000001051085612-V1#section272817141261) can be used for consumable types of products that the user already owned before trying to consume.
