### ISSUE TITLE
[huawei_location] PermissionHandler removed

### ISSUE THREAD

**Issue by deakjahn** [HMS-Core/hms-flutter-plugin#294]
`PermissionHandler` was removed from `huawei_location` and probably others. No deprecation, no additional package instead? Why? You don't expect all of us to create our own platform communication now? It's possible, yes, but why?

**Comment by ilsafarber** [comment]
Hi @deakjahn ,

As you noticed the `PermissionHandler` was removed from the plugins, including `huawei_location`, and it was reported on the `CHANGELOG` files of the related plugins. 

Of course the developers do not expect us to create our own platform communication methods for permissions, there are many useful plugins for requesting such dangerous permissions. Further, the developers probably removed plugin specific permission handlers due to conflicts between plugin's handler and the other permission handler plugins. 

I had such an issue and asked them to remove via online ticket. Since the native kits doesn't have permission handlers on their side, dangerous permissions, whether they are related to Location or not, can be obtained using a single 3rd party permission handler. Many app developers have already imported such plugins while they are building their application thus when compared to using handlers of many different plugins, it is much easier to handle permissions from a single plugin both in code and control wise.

**Comment by deakjahn** [comment]
@ilsafarber In my own case, the question is moot because I simply took the code they removed and put it back into a separate plugin for my own local use (being experienced about plugins, writing and maintaining several of them myself, this was only a small nuisance to me).

However, I consider the move completely erroneous. While you can argue for some general cases, this is a specific Location plugin that needs its own permission as tightly coupled with it as it gets. Besides, Huawei seemingly tries to maintain feature parity with the relevant Google modules -- with good reason -- where they have the same obvious setup.

So, I'm far from convinced, If they really needed, for any strange reason, to separate it out from their modules (as I can see from the issue queue, Location isn't the only one that suffered such a removal), then the obvious step would have been to add their own `huawei_permission` general module and urge developers to use that.
