### ISSUE TITLE
PDF417 reading - flutter-hms-scan

### ISSUE THREAD

**Issue by patv2learn** [HMS-Core/hms-flutter-plugin#33]
I am trying to read PDF417 using flutter-hms-scan but its not working from either camera or selecting image from device storage. Please find attached sample image for the reference. 
![20201026_163857](https://user-images.githubusercontent.com/27989386/97240982-f3618380-17ac-11eb-8d5b-25193d547057.jpg)

I have other samples too if needed please let me know.

**Comment by SerdarCanDev** [comment]
Hi @patv2learn , thank you for reporting the issue. 

We have tested our Flutter plugin with various PDF417 barcodes, both from generators and real-life examples, and the demo project managed to read and successfully parse the PDF417 barcodes. We have tested our native SDK and its demo application and it is also successfully read and parse PDF417 barcodes. Both applications couldn't read your sample. Please check your sample barcode.

**Comment by patv2learn** [comment]
Thanks for the update. I have try to test 10 different US and Canada driving license from Flutter plugin and none of them are working while these all images are working fine with other SDK.

Please try above attached image with https://online-barcode-reader.inliteresearch.com/ online demo for PDF417 and you will see the result.

Is there anyway, I can test native SDK using any demo application?

**Comment by SerdarCanDev** [comment]
Hello again, thank you for your collaboration. 

The barcode scanning process may be affected by environmental conditions such as light, surface, and camera angle, thus please consider trying to scan under different conditions. You may also specify `scanType` as described below (in the Flutter project), in order to improve scanning speed. 

``` dart
DefaultViewRequest reequest = 
    new DefaultViewRequest(scanType: HmsScanTypes.Pdf417);
ScanResponse response = await HmsScanUtils.startDefaultView(request);
```

[This](https://github.com/HMS-Core/hms-scan-demo) is the demo application of Huawei Scan Native SDK, and you may find its documentation from [this link](https://developer.huawei.com/consumer/en/doc/development/HMSCore-Guides/service-introduction-0000001050041994).

If the problem is persistent also in the native SDK, please consider opening an issue on a related GitHub page.

**Comment by patv2learn** [comment]
Thanks SerdarCanDev for the details. As such I have already tried only PDF417 approach with test application and strange thing is some state ID document has 1D and PDF417 both code on it and this change is keep trying to find document without success but if I put a paper or finger on 1D barcode to hide then PDF417 is getting read.

Again, for many US and Canada government issued ID are not reading in your SDK where there are other Web and Mobile SDK is reading them with success. So is there any other property/settings which can try to deep read or improve your SDK readability?

r/Pat

**Comment by SerdarCanDev** [comment]
Hi @patv2learn , thanks again for reporting the issue. Since it's a native SDK problem, a ticket has been submitted to the developer team and currently, they are investigating the issue. 

For now, specifying the `scanType` is the only option for improving the readability and scanning speed. We will provide an update after optimizing the native SDK. Please follow the [pub.dev](https://pub.dev/publishers/developer.huawei.com/packages) for the latest releases.
