### ISSUE TITLE
Map SDK was stripped by minify

### ISSUE THREAD

**Issue by joeccleung** [HMS-Core/hms-flutter-plugin#39]
**Description**
Null reference exception occurs when loading a Huawei Map widget. This only occurs in the minified build.

**Expected behavior**
The Huawei Map widget should be loaded and display a map. 

**Current behavior**
The widget is drawn with empty content. This only occurs in the minified build. 

Non minified build, debug/profile/release build config do work without issue.

**Screenshots**
The location where the null reference exception occurs.
![image](https://user-images.githubusercontent.com/11506048/98707291-b82a8d00-2334-11eb-8693-3b0508c9824b.png)

**Logs**
```
E/MethodChannel#flutter/platform_views(12008): Failed to handle method call
E/MethodChannel#flutter/platform_views(12008): java.lang.NullPointerException: Attempt to invoke virtual method 'void com.huawei.hms.maps.HuaweiMap.setOnInfoWindowClickListener(com.huawei.hms.maps.HuaweiMap$OnInfoWindowClickListener)' on a null object reference
E/MethodChannel#flutter/platform_views(12008): 	at com.huawei.hms.flutter.map.map.MapListenerHandler.setMapListener(MapListenerHandler.java:60)
E/MethodChannel#flutter/platform_views(12008): 	at com.huawei.hms.flutter.map.map.MapController.dispose(MapController.java:257)
```

**Environment**
 - Platform: Flutter
 - Kit: Map
 - Kit Version: 4.0.4+300
 - OS Version: Android 10
 - Android Studio version (if applicable) 4.1
 - Platform version: 1.22.3 (stable) / Dart: 2.10.3
 - Node Version (if applicable)
 - Your Location/Region: Hong Kong

**Other**
 The current workaround is to configure R8 to exclude all HMS Java classes:
`-keep class com.huawei.hms.** { *; }`

**Comment by SerdarCanDev** [comment]
Hi @joeccleung , thank you for reporting the issue. 

minifyEnabled true flag enables code shrinking, obfuscation, and optimization for your project's release build type. While obfuscating the project, HMS Core, and HMS Map is also obfuscated and it should be prevented in order to work without issues.

Before building the APK, configure the obfuscation configuration file to prevent the HMS SDKs from being obfuscated. Please add following attributes to your **proguard-rules.pro file** and then you may use `minifyEnabled true` flag. 

``` 
-ignorewarnings 
-keepattributes *Annotation* 
-keepattributes Exceptions 
-keepattributes InnerClasses 
-keepattributes Signature 
-keep class com.hianalytics.android.**{*;} 
-keep class com.huawei.updatesdk.**{*;} 
-keep class com.huawei.hms.**{*;}
```

After adding proguard-rules.pro file, change your app level build.gradle file described below.

``` gradle
buildTypes {
   release {
      // enables code shrinking, obfuscation, and optimization.
      minifyEnabled true 

      // enables resource shrinking.
      shrinkResources true 

      // the file you added
      proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
   }
}
```

For detailed information you may refer to [Configuring Obfuscation Scripts](https://developer.huawei.com/consumer/en/doc/development/HMSCore-Guides/android-sdk-config-obfuscation-scripts-0000001050158643)
