### ISSUE TITLE
Cannot parse correctly to remoteMessage

### ISSUE THREAD

**Issue by keepfocusontechnology** [HMS-Core/hms-flutter-plugin#40]
**Description**
When my app in background,i can receive ths push message ,but i can not parse the json.There is the error info and i can`t see  which line is reporting an error.
![image](https://user-images.githubusercontent.com/8263580/99251295-09acad80-2848-11eb-907e-5e40e73a79b3.png)

And I can see the `onNotificationOpenedApp` is run,but I can`t get the correct RemoteMessage;

![image](https://user-images.githubusercontent.com/8263580/99252922-bee06500-284a-11eb-86f7-2cf88f1cd782.png)

![image](https://user-images.githubusercontent.com/8263580/99252942-c7d13680-284a-11eb-8748-236da349f134.png)

 

`
flutter (28490): [onNotificationOpenedApp]: {remoteMessage: {data: null, originalUrgency: 2, receiptMode: 0, messageId: null, ttl: 86400, token: null, notification: {titleLocalizationArgs: null, LightSettings: null, icon: null, isLocalOnly: true, title: null, body: null, ChannelId: null, Importance: null, isAutoCancel: true, isDefaultLight: true, BadgeNumber: null, vibrateConfig: null, visibility: null, titleLocalizationKey: null, Color: null, Ticker: null, bodyLocalizationArgs: null, ImageUrl: null, isDefaultSound: true, Sound: null, bodyLocalizationKey: null, When: null, intentUri: null, ClickAction: null, Tag: null, NotifyId: 0, Link: null, isDefaultVibrate: true}, dataOfMap: {}, messageType: null, urgency: 2, contents: 0, collapseKey: null, sentTime: 0, from: null, to: null, sendMode: 0}, uriPage: null, extras: {_push_notifyid: -1398203059, _push_msgid: -1610301640, _push_cmd_type: app}}
`

**Comment by keepfocusontechnology** [comment]
@aktug  HI aktug , may I ask about the progress of this issue?

**Comment by aktug** [comment]
Hello @keepfocusontechnology ,
Push SDK does not expose notification's informations, as you can see there are all null. This is not an issue.
My suggestion as a workaround is;
You can send data messages instead of notification thus you can access all properties of data message then use that values with LocalNotification feature 👍

**Comment by keepfocusontechnology** [comment]
thanks @aktug , The function I want to implement is when my app in background and receive a HW push msg, I click this message and I can parse this message what it Contained data.  

How do I do that?

**Comment by aktug** [comment]
```dart
@override
  void initState() {
    super.initState();
    initPlatformState();
    //...
  }
  Future<void> initPlatformState() async {
    if (!mounted) return;
    Push.onNotificationOpenedApp.listen(_onNotificationOpenedApp);
    var initialNotification = await Push.getInitialNotification();
    _onNotificationOpenedApp(initialNotification);
 }
  void _onNotificationOpenedApp(dynamic initialNotification) {
    print(initialNotification.toString());
  }
```
Thats response is like that : 
```
{
  result: {
    extras: {
      _push_cmd_type: "cosa",
      _push_msgid: "-1744601771",
      _push_notifyid: 1218295586,
      KEY1: "VALUE1",
    },
    remoteMessage: {
      Link: "null",
      NotifyId: "0",
      contents: "0",
      ttl: "86400",
      isDefaultSound: "true",
      ...
    },
    uriPage: "app://app2",
  },
  resultCode: "0",
}
```

You can use "Key-value pair" part so these values come from the extras part

![image](https://user-images.githubusercontent.com/20382405/99374906-25f62c00-28d4-11eb-809b-742481d10544.png)

**Comment by keepfocusontechnology** [comment]
My problem has been solved,Thank you @aktug

**Comment by digitex** [comment]
Hi, I've the same problem.

@keepfocusontechnology How do you solve it?

**Comment by keepfocusontechnology** [comment]
@digitex  Hi, U want to parse the remoteMessage,the first u must config the intent data refer to the official website.

**Comment by NSFriend** [comment]
> ```dart
> ```dart
> @override
>   void initState() {
>     super.initState();
>     initPlatformState();
>     //...
>   }
>   Future<void> initPlatformState() async {
>     if (!mounted) return;
>     Push.onNotificationOpenedApp.listen(_onNotificationOpenedApp);
>     var initialNotification = await Push.getInitialNotification();
>     _onNotificationOpenedApp(initialNotification);
>  }
>   void _onNotificationOpenedApp(dynamic initialNotification) {
>     print(initialNotification.toString());
>   }
> ```
> 
> 
> Thats response is like that :
> {
>   result: {
>     extras: {
>       _push_cmd_type: "cosa",
>       _push_msgid: "-1744601771",
>       _push_notifyid: 1218295586,
>       KEY1: "VALUE1",
>     },
>     remoteMessage: {
>       Link: "null",
>       NotifyId: "0",
>       contents: "0",
>       ttl: "86400",
>       isDefaultSound: "true",
>       ...
>     },
>     uriPage: "app://app2",
>   },
>   resultCode: "0",
> }
> 
> You can use "Key-value pair" part so these values come from the extras part
> ```

Could you please share JSON sample for this request?

**Comment by AhmadIzaz** [comment]
So I have recently implemented the Huawei Push Kit into my app. I have have registered the background callback for background and killed state and it gets invoked as well. But the issue is I get null data in the remote message. Let me create a scenario, I am sending test push from app gallery to my specfic token when the app is in background and I can see that backgroundMessageCallback gets called and in that function I am doing this

 static void backgroundMessageCallback(RemoteMessage remoteMessage) async {
print(
    "MessagingRepositoryHuawei - backgroundMessageCallback: $remoteMessage");
//String data = remoteMessage.data;

Push.localNotification({
  HMSLocalNotificationAttr.TITLE: 'Title',
  HMSLocalNotificationAttr.MESSAGE: 'Message',
  HMSLocalNotificationAttr.DATA: remoteMessage.data,
  HMSLocalNotificationAttr.LARGE_ICON: 'large_icon',
  HMSLocalNotificationAttr.SMALL_ICON:
      'small_icon', 
  
});

I am setting the data that I am getting from the callback into the local push notification as we can see in the code. So the app is in background and I received the notification. Now this is the code I have written to handle the click on the notification.

Push.onNotificationOpenedApp.listen(_onNotificationOpenedApp,
    onError: _onNotificationOpenedAppError,
    onDone: _onNotificationOpenedAppDone);


void _onNotificationOpenedApp(dynamic remoteMessage) {
logger.d("onNotificationOpenedApp: " + remoteMessage.toString());
}

Now I do receive the notification in _onNotificationOpenedApp function but the data param is null. I can see that there is title param and message param and images params as well in the remote message but where is the data values that I set in the backgroundMessageCallback  in local notification. While setting the data in push local notification, I checked and I am setting the actual string like '{'param1':'value1' and so on}' these param in the string are same as I am setting from the console app gallery.

Here is what I get in the _onNotificationOpenedApp 

onNotificationOpenedApp: {remoteMessage: {data: null, originalUrgency: 2, receiptMode: 0, messageId: null, ttl: 86400, token: null, analyticInfo: null, notification: {titleLocalizationArgs: [], LightSettings: [], icon: null, isLocalOnly: true, title: null, body: null, ChannelId: null, Importance: null, isAutoCancel: true, isDefaultLight: true, BadgeNumber: null, vibrateConfig: [], visibility: null, titleLocalizationKey: null, Color: null, Ticker: null, bodyLocalizationArgs: [], ImageUrl: null, isDefaultSound: true, Sound: null, bodyLocalizationKey: null, When: null, intentUri: null, ClickAction: null, Tag: null, NotifyId: 0, Link: null, isDefaultVibrate: true}, dataOfMap: {}, messageType: null, urgency: 2, contents: 0, collapseKey: null, analyticInfoMap: {}, sentTime: 0, from: null, to: null, sendMode: 0}, uriPage: null, extras: {notification: {data: {}, color: null, importance: max, sound: null, vibrate: true, title: Notification Title, userInteractio

along with this **W/HMSSDK_RemoteMessage( 3714): JSONException:parse message body failed.**
