### ISSUE TITLE
The 5.0.3 account update is broken

### ISSUE THREAD

**Issue by konstantintuev** [HMS-Core/hms-flutter-plugin#45]
**Description**
MissingPluginException(No implementation found for method signIn on channel huawei_account)

**Expected behavior**
To work

**Current behavior**
It doesn't work

**Logs**
`I/flutter (24234): MissingPluginException(No implementation found for method signIn on channel huawei_account)
I/flutter (24234): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:157:7)
I/flutter (24234): <asynchronous suspension>
I/flutter (24234): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:332:12)
I/flutter (24234): #2      HmsAccount.signIn (package:huawei_account/hms_account.dart:58:24)`

**Environment**
 - Platform: Flutter
 - Kit: Account
 - Kit Version 5.0.3
 - OS Version Android 10
 - IntelliJ version 2020.3

**Comment by konstantintuev** [comment]
And trying to rollback to ^5.0.0+300 somehow doesn't work so I am stuck with a broken dependency **AGAIN**

**Comment by konstantintuev** [comment]
The ads kit is incomplete and I have my own fork, the first version of the push kit was so broken I had to rewrite it and integrate it deeply in my project so now I can't update...
I have fixed so many issues locally because the software quality is awful and you know what -  Google sdks just work on both iOS and Android while so many things are just broken on Huawei!

**Comment by cagdasmer** [comment]
Hello @konstantintuev, 
Thank you for reporting the issue. We identified the problem with the recent upgrade and will fix it.

Meanwhile you can do the following:

The reason you are getting the exceptions is because you are probably trying to use the methods from `'package:huawei_account/hms_account.dart'`. Which is no longer used.

Please try importing 
`'package:huawei_account/huawei_account.dart'` 
and use the methods from the **new modules**. You can read more about the modules and their functionalities from [Huawei Developer Website](https://developer.huawei.com/consumer/en/doc/development/HMS-Plugin-Guides/version-change-history-0000001050726410) or the [readme file](https://github.com/HMS-Core/hms-flutter-plugin/tree/master/flutter-hms-account#hmsauthservice) in the repository.

Let us know how it goes.

**Comment by konstantintuev** [comment]
It's fixed!
