### ISSUE TITLE
onMessageReceivedStream on background mode

### ISSUE THREAD

**Issue by ensarduman** [HMS-Core/hms-flutter-plugin#63]
```
  Future initStreamListeners() async {
    Push.getIntentStream.listen(_onNewIntent, onError: _onIntentError);
    Push.onLocalNotificationClick.listen(_onNotificationClick);
    Push.onNotificationOpenedApp.listen(_onNotificationOpenedApp);
    var initialNotification = await Push.getInitialNotification();
    _onNotificationOpenedApp(initialNotification);
    String intent = await Push.getInitialIntent();
    _onNewIntent(intent);
    Push.onMessageReceivedStream.listen(_receiveRemoteMessage, onError: _onMessageReceiveError);
    Push.getRemoteMsgSendStatusStream.listen(_onRemoteMessageSendStatus, onError: _onRemoteMessageSendError);
    bool backgroundMessageHandler = await Push.registerBackgroundMessageHandler(_receiveBackgroundRemoteMessage);
    print("backgroundMessageHandler registered: $backgroundMessageHandler");
  }

  void _receiveRemoteMessage(RemoteMessage remoteMessage) async {
    String data = remoteMessage.data;
    var huaweiNotificationHandler = HuaweiNotificationActionHandler();
    huaweiNotificationHandler.handleReceivedNotification(data);
  }

  static void _receiveBackgroundRemoteMessage(RemoteMessage remoteMessage) async {
    String data = remoteMessage.data;
    var huaweiNotificationHandler = HuaweiNotificationActionHandler();
    huaweiNotificationHandler.handleReceivedBackgroundNotification(data);
  }
```

Hi, normally i use onMessageReceivedStream for data updates when application alive and of course this function works perfectly. But if app is running on background,  receiveBackgroundRemoteMessage function works. The problem is that actually my application is working that time and in  receiveBackgroundRemoteMessage function i can't reach my static variables or my state because this function bhaves like application is killed but in fact app is alive, i can debug even my socket communications. I also debug _receiveBackgroundRemoteMessage but i can't reach my state and static variables.

I think that on background but application is not killed state so it must be used with onMessageReceivedStream and at least runs _receiveBackgroundRemoteMessage function.

By the way, I use this lib only for android.

Thanks

**Comment by aktug** [comment]
Hi @ensarduman 
We're trying to understand where comes from this situation and then we'll release a patch version of that,
thank you for your interest 👍

**Comment by atavci** [comment]
Hello @ensarduman 👋,

The background message callback triggers a separate dart isolate than the main Flutter isolate which keeps your application and since the dart isolates doesn't share memory it is normal that you can't reach your state and other variables that declared in your application from the background callback. This is a limitation for background messages because they can be obtained on killed state when there is no Flutter application present so they should have their own isolate by the time being. 

As you point out, when the application is in killed or on background state, the receiveBackgroundRemoteMessage callback will be triggered. This is because the plugin checks if the application is on foreground before it sends the message to the Flutter. As i know it doesn't take too much time for a Flutter application to become idle after it is backgrounded, so even if the messages received from the onMessageReceivedStream there is a big chance that your state could not be reached, you can test this on a release apk because debug mode keeps the application alive even if it is on background. 

If you think that the expected behaviour should be able to receive the messages from onMessageReceivedStream while the application is on background, we would like to know more about the your use case before considering to change this behaviour.

Thank you for the awesome question.
