### ISSUE TITLE
onRemoteMessageReceiveErrortype 'List<dynamic>' is not a subtype of type 'List<String>'

### ISSUE THREAD

**Issue by anilari** [HMS-Core/hms-flutter-plugin#69]
**Description**
I am using custom data with my push notification. It works with Firebase but not working with HMS

**Expected behavior**
I should parse my push message successfully.

**Current behavior**
What actually happened？

**Screenshots**
I/SecurityComp10105306: BksUtil(16785): get bks from tss begin
I/SecurityComp10105306: BksUtil(16785): hms version code is : 5.1.1.303
I/SecurityComp10105306: BksUtil(16785): bks not update
I/SecurityComp10105306: BksUtil(16785): getFilesBksIS 

**Logs**
I/flutter (16785): Push token: 6470a97c83106830f8d91f3b795cabf8487e97a4
I/flutter (16785): [onNotificationOpenedApp]null
I/flutter (16785): rawHandle 2416509491933118492
I/flutter (16785): rawCallback -6109594799218979051
I/HmsFlutterPush(16785): BackgroundMessageHandler registered ✔
I/flutter (16785): backgroundMessageHandler registered: true
I/HMSSDK_HmsMessageService(16785): start to destroy
I/flutter (16785): **onRemoteMessageReceiveErrortype 'List<dynamic>' is not a subtype of type 'List<String>'**

**Environment**
 - Platform: Flutter
 - Kit: Push
 - Kit Version ^5.0.2+303
 - OS Version Android 10 JNY-LX1

**Comment by anilari** [comment]
[https://i.ibb.co/KDywCyJ/Screen-Shot-2021-02-27-at-17-37-13.png](url)

**Comment by anilari** [comment]
When I change 4 lines of remote_message.dart to dynamic it works.

  final List<dynamic> lightSettings;
  final List<dynamic> vibrateConfig;
  final List<dynamic> titleLocalizationArgs;
  final List<dynamic> bodyLocalizationArgs;

**Comment by atavci** [comment]
Hello @anilari 👋,

I've checked the HUAWEI Push SDK's Android Native API Reference. In the [Remote Message](https://developer.huawei.com/consumer/en/doc/development/HMSCore-References-V5/remotemessage-notification-0000001050255662-V5) document it is stated that the **lightSettings** parameter is type of **int[]** on Java which is corresponds to **List\<int>** on Dart but in the [REST Guide](https://developer.huawei.com/consumer/en/doc/development/HMSCore-References-V5/https-send-api-0000001050986197-V5#EN-US_TOPIC_0000001124288117__p20908173320169) the **light_settings** parameter is stated as type of **object** in the request parameter. Maybe this parameter type difference between the Android Notification Structure and RemoteMessage.Notification causes the issue but I can't make sure of this because I can not reproduce your issue. 

Can you provide a sample to reproduce this issue ? This sample can include the request parameters if you are using the REST API or the configurations that you made in order to receive the notification message from the onMessageReceived API since this callback would be normally only triggered on Data Messages without a notification payload.

Thank you very much for pointing out this issue 👍 after we reproduce it we can come up with a solution and provide a fix on our upcoming releases.

**Comment by anilari** [comment]
Hello, I produce this error with just using wonderpush api. Wonderpush side triggers HMS and GMS together. So I don't have any information about what exactly goes to the HMS but When I check error it points out that lines should implemented dynamic. Otherwise it crashes and not able to get push notification.

Thank You,
Anıl

**Comment by atavci** [comment]
Hello again Anıl, I have implemented the WonderPush to a demo project and tried to reproduce your issue but the onMessageReceive callback is never got triggered even if I able to receive the push notifications that sent from the WonderPush API. Apart from this I have triggered the onMessageReceive callback with a notification message with the **foreground_show** field as false. This is the only way to internally trigger the callback with a message that includes notification, otherwise it will be handled by the system and will be posted on the Notification Tray (NC) as stated in the following documents:

**Comment by anilari** [comment]
Hello, You need to also implement hms plugins to your flutter project. Otherwise it won't work. I am sending my push data privately to you.

**Comment by atavci** [comment]
Hello again, Unlike the native push sdk, It seems that the Wonderpush API can trigger the SDK's `onMessageReceived` callback with a push notification and thus able to obtain its data.  In this process, fields you have mentioned before are reaching Flutter with a different type than the native SDK and this causes the mismatch. We are converting these fields to be dynamic in order to support WonderPush integration and eliminate further parsing errors. Be sure to check out our next release that will include this update (next version will be 5.0.2+304).

Thank you very much for your contribution and your interest on the push plugin. 👍
