### ISSUE TITLE
NullPointerException in PluginContext.java

### ISSUE THREAD

**Issue by peter9teufel** [HMS-Core/hms-flutter-plugin#92]
**Description**
The app logs a lot of crashes in our crashlytics platform caused by a NullPointer Exception in PluginContext.java

**Expected behavior**
App not crashing

**Current behavior**
App seems to crash (18.000 in 1 week on ~60 affected users) though I wasn't able to reproduce the crash on a Huawei Mate 20 Lite which I have set up without Google Services to test the HMS integration in our flutter app.

**Logs**
`
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object java.lang.ref.WeakReference.get()' on a null object reference
       at com.huawei.hms.flutter.push.hms.PluginContext.getContext(PluginContext.java:36)
       at com.huawei.hms.flutter.push.hms.FlutterHmsMessageService.onTokenError(FlutterHmsMessageService.java:87)
       at com.huawei.hms.push.HmsMessageService.a(HmsMessageService.java:34)
       at com.huawei.hms.push.HmsMessageService.a(HmsMessageService.java:29)
       at com.huawei.hms.push.HmsMessageService.handleIntentMessage(HmsMessageService.java:7)
       at com.huawei.hms.push.HmsMessageService$a.handleMessage(HmsMessageService.java:7)
       at android.os.Handler.dispatchMessage(Handler.java:110)
       at android.os.Looper.loop(Looper.java:219)
       at android.app.ActivityThread.main(ActivityThread.java:8387)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1055)
`

**Environment**
 - Platform: Flutter
 - Kit: Push (huawei_push)
 - Kit Version 5.1.1+301
 - OS Version Android 10
 - 
**Other**
Any help on how to track down that bug or what may cause it would be highly appreciated.

Thanks a lot for your support.

BG,
Peter

**Comment by atavci** [comment]
Hello Peter,

I believe this error might be thrown when the application receives a data message or tries to obtain a push token in the background/killed state as similar with the issue #73. The Push Kit's service can be triggered in the background/killed state where there is no app context which can cause this error.

Can I ask for the information below for me to reproduce the issue and confirm that this issue is caused by the reason that I've mentioned.

* Flutter version.
* Is the Auto-Initialization feature of the Push Kit enabled ?
* If available, EMUI and Android version of the device that logged the error.

Thank you for reporting this issue.

Best.

**Comment by peter9teufel** [comment]
Hi,
Thanks for your quick reply!

Crashlytics only shows "Android 10" and no further details regarding the version but it states that 100% of those crashes happen while the app is in background. Auto-Initialization is enabled via AndroidManifest, I'm now disabling it as the app now checks for presence of google and huawei services and decides whether to obtain a huawei push token or not.

**Information for app that causes the crash:**
Flutter Version: 2.0.6
Auto-Initialization: enabled
Android Version: 10

Best,
Peter

**Comment by atavci** [comment]
Hello again,

By the information you provided, I can confirm that this issue is indeed related to the push service automatically obtaining tokens on background where there is no flutter app context.

I have a quick fix that would solve your problem: in the `PluginContext.java` file of the plugin you can change the line 36 from
```
return weakReference.get();
```
to 
```
return weakReference != null ? weakReference.get() : null;
```

This change should fix your issue. If the error persists feel free to inform us and keep this issue open.

Best.

**Comment by peter9teufel** [comment]
Hi,
for the current app update I have disabled auto initialization as the app handles those things on each app start depending on the device, available services, etc. so I guess the background crashes shouldn't happen with this update. As we have got 0 crash reports in our support desk I can guarantee that this crash happens only in Background execution and checking your code suggestion in quick local tests this should really fix the crash.

Thanks for your quick reply.

Best,
Peter
